[project]
name = "ot-ai-api"
version = "0.1.0"
description = "API for Open Targets serving as a centralized hub for AI-driven endpoints"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["fastapi>=0.115.3", "requests>=2.32.3", "uvicorn>=0.32.0"]
